### ISSUE TITLE
Explanation of suitability of decision tree model to our analysis

### ISSUE THREAD

**Issue by talhaadnan100** [UBC-MDS/Breast-Cancer-Prediction#12]
Incorporate advisor's feedback to Readme:

> Why do you think decision tree model is suitable for your analysis?

**Comment by talhaadnan100** [comment]
@akanshaVashisth the explanation for choosing decision tree classification is as follows:

>We choose decision tree classification for our analysis primarily because of our knowledge and experience of using this predictive technique in the past. We are most familiar with its hyperparameters and have incorporated optimization of maximum depth and minimum samples split in our analysis. Additionally, our exploration of the data has confirmed our choice for decision tree classification based on the following reasons:
> 1.	Predictions are made on one categorical variable with two possible options only i.e. binary classification.
> 2.	The size of the data set is very small (<150 examples).
> 3.	All features are positive continuous variable.

Kindly choose the issue after reviewing.

**Comment by akanshaVashisth** [comment]
Great explanation!
