### ISSUE TITLE
EDA saves to root directory

### ISSUE THREAD

**Issue by talhaadnan100** [UBC-MDS/Breast-Cancer-Prediction#19]
`eda.py` is saving all the figures to root directory of the project. I have identified line 31 of the code is causing it:

`plt.savefig('plot'+str(i)+'.png')`

Please make use of the `parser.add_argument('output_file')` so that the files are saved to the desired folder can be specified when called in the script.

**Comment by talhaadnan100** [comment]
Nothing some other bugs in `eda.py`:

1. the `plotMCP1.png` does not output after running `read_clean.py`
2. plots don't include legend healthy controls vs. patients

**Comment by akanshaVashisth** [comment]
Fixed the script (0d5eec180d51a561d4bc0cf7c8420e6806567614)
