### ISSUE TITLE
Gathered feedback

### ISSUE THREAD

**Issue by talhaadnan100** [UBC-MDS/Breast-Cancer-Prediction#29]
Recording the feedback received from Daniel and Phuntsok:
- [x] smaller cross validation fold
- [x] insert random state when in building model
- [ ] Include confusion matrix, and report recall and precision.

**Comment by akanshaVashisth** [comment]
Feedback received from Sayanti and Fan: 

- [ ] Combination of features.

- [ ] Connection between EDA and results.

**Comment by akanshaVashisth** [comment]
Regarding combination of features : Mentioned in future directions in the final report.

**Comment by akanshaVashisth** [comment]
Regarding : Include confusion matrix, and report recall and precision, we will be addressing this in upcoming week.
