### ISSUE TITLE
Feedback on Milestone 2

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/Breast-Cancer-Prediction#34]
@akanshaVashisth and @talhaadnan100, great job on Milestone 2! All I can add is the following:

- [x] Include instructions on how to run your analysis with make on the main readme

**Suggestions:**

- Go through http://swcarpentry.github.io/make-novice/reference. This would help you make your Make code more practical. For example, you can use automatic variables and avoid some repetition.

**Comment by akanshaVashisth** [comment]
Thank you for the feedback and guidance Ozum,
We have Updated README.
